name: x
channels:
  - conda-forge
  - fastai
dependencies:
  - python=3.9
  - pip
  - autograd>=1.3
  - fastcore
  - ipykernel
  - ipywidgets==7.7.1
  - jax
  - jaxlib
  - matplotlib>=3.0.3
  - nbdev
  - nbstripout
  - numpy>=1.16.2
  - openssl
  - papermill
  - pre-commit
  #- pymkl>=0.0.3
  - rsync
  - scikit-image
  - scipy
  - pip:
    - ceviche
    - javiche
    - ceviche_challenges