# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/11_ceviche_challenges.ipynb.

# %% auto 0
__all__ = ['border_bias']

# %% ../notebooks/11_ceviche_challenges.ipynb 14
import scipy.ndimage
def border_bias(model):
  width = 5
  inner = np.s_[width:-width,width:-width]
  dr = np.array(model.design_region_coords).reshape((2,2))
  bg = model.density_bg[dr[0,0]-1:dr[1,0]+1, dr[0,1]-1:dr[1,1]+1]

  border_density = np.zeros(model.design_region_shape)[inner]
  for direction in range(2):
    for sign in [-1, 1]:
      border_density+= np.roll(bg, sign*(width+1), direction)[inner][1:-1,1:-1]
  
  border_density = np.pad(border_density, mode='edge', pad_width=width)
  border_density = border_density*2-1
  border_density[inner] = 0
  border_density = scipy.ndimage.gaussian_filter(border_density, 1)
  border_density[inner] = 0
  border_mask = np.zeros_like(border_density)
  border_mask[inner] = 1
  return border_density, border_mask
